### PR TITLE
Fix cargo unaligned warnings

### PR DESCRIPTION
**Pull request by dhriti-rajan**
Fixing issue https://github.com/rust-vmm/linux-loader/issues/130.

### CODE REVIEW

**Review by rbradford — COMMENTED** [review]
Thank you for your contribution. It might be worth regenerating this file with newer bindgen which which hopefully resolve this issue instead.

**Comment by dhriti-rajan** [comment]
Thanks for the tip!  I've regenerated the file with a newer bindgen version, but am still working on cleaning it up since regenerating it seems to have resulted in a couple errors.  I'll unmark the PR as a draft once I get it building again and make sure it passes the tests.  Sorry for taking a while on this, I'll try to get it wrapped up soon.

**Comment by aghecenco** [comment]
This PR will have to get merged first as the warnings it fixes have since been "promoted" to errors and all PRs are going to fail following the container image update included in #151 (also failing for the same reason).

**Comment by andreeaflorescu** [comment]
This PR needs a significant rework. I am closing it for now, but @dhriti-rajan if you want to continue working on it, feel free to reopen. Thanks!

**Pull request closed without merging**
